// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace luxifer.Scaleway.Inputs
{

    public sealed class MnqCredentialSqsSnsCredentialsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the key.
        /// </summary>
        [Input("accessKey")]
        public Input<string>? AccessKey { get; set; }

        /// <summary>
        /// List of permissions associated to this Credential. Only one of permissions may be set.
        /// </summary>
        [Input("permissions")]
        public Input<Inputs.MnqCredentialSqsSnsCredentialsPermissionsArgs>? Permissions { get; set; }

        /// <summary>
        /// The Secret value of the key.
        /// </summary>
        [Input("secretKey")]
        public Input<string>? SecretKey { get; set; }

        public MnqCredentialSqsSnsCredentialsArgs()
        {
        }
        public static new MnqCredentialSqsSnsCredentialsArgs Empty => new MnqCredentialSqsSnsCredentialsArgs();
    }
}
